modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Gorbyas/VH_Mining_Speedometer/issues"

[[mods]]
modId="miningspeedometer"
version="${file.jarVersion}"
displayName="VH Mining Speedometer"
logoFile="icon.png"
description='''
This mod adds a "/speedometer modid:block" command, which takes into consideration effects on the player and the tool held in hand to determine how much mining speed is needed to instamine the block.

Special thanks to JustAHuman for helping me with this little project.
'''
displayURL="https://github.com/Gorbyas/VH_Mining_Speedometer"
credits="shiftthedev"
authors="Gorbyas, JustAHuman"

[[dependencies.miningspeedometer]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.miningspeedometer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"
